name: Sync `api-docs` directory to ReadMe

# Run workflow for every push to the `main` branch
on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      # Run GitHub Action to sync docs in `documentation` directory
      - name: Sync API docs
        # We recommend specifying a fixed version, i.e. @v10
        # Docs: https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions
        uses: readmeio/rdme@v10
        with:
          rdme: docs upload ./api-docs --key=${{ secrets.README_API_KEY }} --branch=1.0

      # Run GitHub Action to sync docs in `documentation` directory
      - name: Sync Guides
        # We recommend specifying a fixed version, i.e. @v10
        # Docs: https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions
        uses: readmeio/rdme@v10
        with:
          rdme: docs upload ./guides --key=${{ secrets.README_API_KEY }} --branch=1.0

      # Run GitHub Action to sync docs in `documentation` directory
      - name: Sync custom pages docs
        # We recommend specifying a fixed version, i.e. @v10
        # Docs: https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions
        uses: readmeio/rdme@v10
        with:
          rdme: custompages upload ./custompages --key=${{ secrets.README_API_KEY }}

      # Run GitHub Action to sync changelogs in `changelog` directory
      - name: Sync changelog pages docs
        # We recommend specifying a fixed version, i.e. @v10
        # Docs: https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions
        uses: readmeio/rdme@v10
        with:
          rdme: changelog upload ./changelogs --key=${{ secrets.README_API_KEY }}
